repository_type: pipeline

nf_core_version: 3.2.0

lint:
  files_unchanged:
    - .github/CONTRIBUTING.md
    - .github/CONTRIBUTING.md
    - CODE_OF_CONDUCT.md
    - assets/nf-core-fieldbioinformatics-nf_logo_light.png
    - docs/images/nf-core-fieldbioinformatics-nf_logo_light.png
    - docs/images/nf-core-fieldbioinformatics-nf_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - validation.help.beforeText
    - validation.help.afterText
    - validation.summary.beforeText
    - validation.summary.afterText
  multiqc_config:
    - report_comment
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - CODE_OF_CONDUCT.md
    - assets/nf-core-fieldbioinformatics-nf_logo_light.png
    - docs/images/nf-core-fieldbioinformatics-nf_logo_light.png
    - docs/images/nf-core-fieldbioinformatics-nf_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml

template:
  org: artic-network
  name: fieldbioinformatics-nf
  description: Amplicon genome assembly which doesn't suck
  author: Sam Wilkinson
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - igenomes
    - gitpod
    - codespaces
    - fastqc
  is_nfcore: false
