lint:
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - CODE_OF_CONDUCT.md
    - assets/nf-core-amplicon-nf_logo_light.png
    - docs/images/nf-core-amplicon-nf_logo_light.png
    - docs/images/nf-core-amplicon-nf_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  files_unchanged:
    - .github/CONTRIBUTING.md
    - .github/CONTRIBUTING.md
    - CODE_OF_CONDUCT.md
    - assets/nf-core-amplicon-nf_logo_light.png
    - docs/images/nf-core-amplicon-nf_logo_light.png
    - docs/images/nf-core-amplicon-nf_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
  multiqc_config:
    - report_comment
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - validation.help.beforeText
    - validation.help.afterText
    - validation.summary.beforeText
    - validation.summary.afterText
  template_strings:
    - assets/sample_report_template.html
    - assets/run_report_template.html
nf_core_version: 3.3.1
repository_type: pipeline
template:
  author: Sam Wilkinson
  description: Amplicon genome assembly which doesn't suck
  force: false
  is_nfcore: false
  name: amplicon-nf
  org: artic-network
  outdir: .
  skip_features:
    - igenomes
    - gitpod
    - codespaces
    - fastqc
  version: 1.0.0dev
